### ISSUE TITLE
Matplotlib's unyt support breaks when plotting zero-length arrays

### ISSUE THREAD

**Issue by JBorrow** [yt-project/unyt#179]
* unyt version: unyt==2.7.1
* Python version: numpy==1.19.0 python==3.8.0, matplotlib==3.2.2
* Operating System: MacOS and Linux

### Description

When using `matplotlib_support`, if we plot an empty unyt array, matplotlib breaks when changing the units. See the below case.

We have people interested in helping fix this but don't know if it's an unyt problem or a matplotlib problem.

### What I Did

The breaking case:
```python
import unyt
import matplotlib.pyplot as plt
import numpy as np

x = unyt.unyt_array([1, 2, 3], units="Mpc")
y = unyt.unyt_array([1, 2, 3], units="Solar_Mass")

mask = np.array([False, False, False])

x_lims = unyt.unyt_array([0, 1], units="Mpc")

 with unyt.matplotlib_support:
     plt.plot(x[mask], y[mask])
     plt.xlim(*x_lims)
```
Full traceback:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-10-5f09c5659620> in <module>
      1 with unyt.matplotlib_support:
      2     plt.plot(x[mask], y[mask])
----> 3     plt.xlim(*x_lims)
      4 

~/.pyenv/versions/3.8.0/lib/python3.8/site-packages/matplotlib/pyplot.py in xlim(*args, **kwargs)
   1394     if not args and not kwargs:
   1395         return ax.get_xlim()
-> 1396     ret = ax.set_xlim(*args, **kwargs)
   1397     return ret
   1398 

~/.pyenv/versions/3.8.0/lib/python3.8/site-packages/matplotlib/axes/_base.py in set_xlim(self, left, right, emit, auto, xmin, xmax)
   3181             right = xmax
   3182 
-> 3183         self._process_unit_info(xdata=(left, right))
   3184         left = self._validate_converted_limits(left, self.convert_xunits)
   3185         right = self._validate_converted_limits(right, self.convert_xunits)

~/.pyenv/versions/3.8.0/lib/python3.8/site-packages/matplotlib/axes/_base.py in _process_unit_info(self, xdata, ydata, kwargs)
   2071             return kwargs
   2072 
-> 2073         kwargs = _process_single_axis(xdata, self.xaxis, 'xunits', kwargs)
   2074         kwargs = _process_single_axis(ydata, self.yaxis, 'yunits', kwargs)
   2075         return kwargs

~/.pyenv/versions/3.8.0/lib/python3.8/site-packages/matplotlib/axes/_base.py in _process_single_axis(data, axis, unit_name, kwargs)
   2054                 # We only need to update if there is nothing set yet.
   2055                 if not axis.have_units():
-> 2056                     axis.update_units(data)
   2057 
   2058             # Check for units in the kwargs, and if present update axis

~/.pyenv/versions/3.8.0/lib/python3.8/site-packages/matplotlib/axis.py in update_units(self, data)
   1514         neednew = self.converter != converter
   1515         self.converter = converter
-> 1516         default = self.converter.default_units(data, self)
   1517         if default is not None and self.units is None:
   1518             self.set_units(default)

~/.pyenv/versions/3.8.0/lib/python3.8/site-packages/unyt/mpl_interface.py in default_units(x, axis)
    108             # label in the subsequent call to axisinfo
    109             unyt_arrayConverter._axisnames[axis] = name if name is not None else ""
--> 110             return x.units
    111 
    112         @staticmethod

AttributeError: 'tuple' object has no attribute 'units'
```

**Comment by JBorrow** [comment]
FWIW this also breaks with `pint`, but in a different way:
```python
import pint
import matplotlib.pyplot as plt
import numpy as np

ureg = pint.UnitRegistry()
ureg.setup_matplotlib()

x = [1, 2, 3] * ureg.meter
y = [1, 2, 3] * ureg.g

mask = np.array([False, False, False])

x_lims = [0, 1] * ureg.meter

plt.plot(x[mask], y[mask])
plt.xlim(*x_lims)
```
Leads to
```
Traceback (most recent call last):
  File "test_pint.py", line 15, in <module>
    plt.plot(x[mask], y[mask])
  File "/Users/mphf18/.pyenv/versions/3.8.0/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2761, in plot
    return gca().plot(
  File "/Users/mphf18/.pyenv/versions/3.8.0/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 1647, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/Users/mphf18/.pyenv/versions/3.8.0/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 216, in __call__
    yield from self._plot_args(this, kwargs)
  File "/Users/mphf18/.pyenv/versions/3.8.0/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 337, in _plot_args
    self.axes.xaxis.update_units(x)
  File "/Users/mphf18/.pyenv/versions/3.8.0/lib/python3.8/site-packages/matplotlib/axis.py", line 1516, in update_units
    default = self.converter.default_units(data, self)
  File "/Users/mphf18/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pint/matplotlib.py", line 59, in default_units
    return getattr(x[0], "units", None)
  File "/Users/mphf18/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pint/quantity.py", line 1834, in __getitem__
    return type(self)(self._magnitude[key], self._units)
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by JBorrow** [comment]
Also, I know that this may seem crazy - why on earth would somebody create an empty plot and then change the units - but this is crashing in our pipeline that automatically produces plots. We have some cases where for some figures there happen to be zero objects to plot.

**Comment by ngoldbaum** [comment]
It looks like the error is coming from inside of unyt, indicating that fix is likely straightforward. I probably won’t look at this for a while but will happily merge a PR that adds support for this along with a test.
