### ISSUE TITLE
Attempting to define capacitance unit Farad raises UnitsNotReducible.

### ISSUE THREAD

**Issue by l-johnston** [yt-project/unyt#53]
* unyt version: 1.0.7
* Python version: 3.6.6
* Operating System: Win10

### Description

I tried to define the capacitance unit Farad.

### What I Did

```
import unyt as u

u.define_unit('F', (1.0, 'C/V'), r'\rm{F}', None, True)
---------------------------------------------------------------------------
MKSCGSConversionError                     Traceback (most recent call last)
c:\Python\projects\unyt\unyt\array.py in in_base(self, unit_system)
    897             conv_data = _check_em_conversion(
--> 898                 self.units, unit_system=us, registry=self.units.registry)
    899         except MKSCGSConversionError:

c:\Python\projects\unyt\unyt\unit_object.py in _check_em_conversion(unit, to_unit, unit_system, registry)
    810             else:
--> 811                 raise MKSCGSConversionError(unit)
    812     return em_map

MKSCGSConversionError: The 'C/V' unit cannot be safely converted.

During handling of the above exception, another exception occurred:

UnitsNotReducible                         Traceback (most recent call last)
<ipython-input-2-452d0c29d592> in <module>
----> 1 u.define_unit('F', (1.0, 'C/V'), r'\rm{F}', None, True)

c:\Python\projects\unyt\unyt\unit_object.py in define_unit(symbol, value, tex_repr, offset, prefixable, registry)
    987             raise RuntimeError("\"value\" needs to be a quantity or "
    988                                "(value, unit) tuple!")
--> 989     base_value = float(value.in_base(unit_system='mks'))
    990     dimensions = value.units.dimensions
    991     registry.add(symbol, base_value, dimensions, prefixable=prefixable,

c:\Python\projects\unyt\unyt\array.py in in_base(self, unit_system)
    898                 self.units, unit_system=us, registry=self.units.registry)
    899         except MKSCGSConversionError:
--> 900             raise UnitsNotReducible(self.units, unit_system)
    901         if any(conv_data):
    902             to_units, (conv, offset) = _em_conversion(

UnitsNotReducible: The unit "C/V" (dimensions "(current_mks)**2*(time)**4/((length)**2*(mass))") cannot be reduced to an expression within the mks system of units.
```

**Comment by ksunden** [comment]
Seems to be the current as the problem.

A slightly simpler definition which presents the same problem:

```
>>> u.define_unit('F', (1.0, 'A/m'), r'\rm{F}')
Traceback (most recent call last):
  File "/home/kyle/venvs/source/unyt/unyt/array.py", line 898, in in_base
    self.units, unit_system=us, registry=self.units.registry)
  File "/home/kyle/venvs/source/unyt/unyt/unit_object.py", line 811, in _check_em_conversion
    raise MKSCGSConversionError(unit)
unyt.exceptions.MKSCGSConversionError: The 'A/m' unit cannot be safely converted.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kyle/venvs/source/unyt/unyt/unit_object.py", line 989, in define_unit
    base_value = float(value.in_base(unit_system='mks'))
  File "/home/kyle/venvs/source/unyt/unyt/array.py", line 900, in in_base
    raise UnitsNotReducible(self.units, unit_system)
unyt.exceptions.UnitsNotReducible: The unit "A/m" (dimensions "(current_mks)/(length)") cannot be reduced to an expression within the mks system of units.
```

**Comment by ngoldbaum** [comment]
Sigh... This MKS/CGS conversion stuff continues to bite us in the butt.

Thanks for reporting! I will try to take a look at this today.

**Comment by l-johnston** [comment]
The trouble is in `_check_em_conversion()`  where it is unable to deal with a unit that is an expression containing E&M units. In this case, we aren't trying to convert the unit(s), yet the function raises an error despite the intention stated in the doc string.

One solution is to add capacitance, inductance, etc. to the default registry and this does work; but, what about other cases? For example, a user may want to define V/sqrt(Hz) just for the latex representation.

**Comment by ngoldbaum** [comment]
Right, Farad should definitely be included by default, that was an oversight.

It should be possible to define units like `V/sqrt(Hz)` and the code path that's being hit right now should only get hit if you try to convert it to a CGS E&M unit (e.g. `statV/sqrt(Hz)`). The fact it's hitting this code path right now and raising an exception in this way is a bug. We dealt with similar issues in the past.

Ultimately the source of the trouble is that we want to make it possible to do things like `array_in_gauss.to('T')` but doing that in a way that's not fragile is difficult, and unfortunately it's not possible in general to convert between CGS and SI E&M units.
